definitions:
  reqDto.Captcha:
    properties:
      content:
        type: string
      id:
        type: string
    type: object
  reqDto.NewUserLogin:
    properties:
      captcha:
        $ref: '#/definitions/reqDto.Captcha'
      message:
        $ref: '#/definitions/reqDto.TextMessage'
      method:
        type: string
      password:
        type: string
      phone:
        type: string
      revoke:
        type: boolean
    required:
    - method
    - phone
    - revoke
    type: object
  reqDto.TextMessage:
    properties:
      code:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/{id}:
    get:
      description: 获取指定用户的信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 返回结果
          schema:
            type: Object
        "400":
          description: 请求错误
          schema:
            type: Object
      summary: 获取用户信息
      tags:
      - 用户信息
  /api/user/login:
    post:
      description: 登录
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/reqDto.NewUserLogin'
      responses:
        "200":
          description: 返回结果
          schema:
            type: Object
        "400":
          description: 请求错误
          schema:
            type: Object
      summary: 登录
      tags:
      - 用户信息
swagger: "2.0"
